-- Insere marcas no banco de dados (caso ainda não estejam na tabela "marcas")
INSERT INTO public.marcas (id, nome, cadastro, ativo) VALUES
    (1, 'Chevrolet', CURRENT_TIMESTAMP, true),
    (2, 'Ford', CURRENT_TIMESTAMP, true),
    (3, 'Toyota', CURRENT_TIMESTAMP, true),
    (4, 'Honda', CURRENT_TIMESTAMP, true),
    (5, 'Ferrari', CURRENT_TIMESTAMP, true),
    (6, 'BMW', CURRENT_TIMESTAMP, true),
    (7, 'Mercedes-Benz', CURRENT_TIMESTAMP, true),
    (8, 'Volkswagen', CURRENT_TIMESTAMP, true),
    (9, 'Audi', CURRENT_TIMESTAMP, true),
    (10, 'Porsche', CURRENT_TIMESTAMP, true),
    (11, 'Lamborghini', CURRENT_TIMESTAMP, true),
    (12, 'Maserati', CURRENT_TIMESTAMP, true),
    (13, 'Alfa Romeo', CURRENT_TIMESTAMP, true),
    (14, 'Fiat', CURRENT_TIMESTAMP, true),
    (15, 'Tesla', CURRENT_TIMESTAMP, true),
    (16, 'Jeep', CURRENT_TIMESTAMP, true),
    (17, 'Dodge', CURRENT_TIMESTAMP, true),
    (18, 'Chrysler', CURRENT_TIMESTAMP, true),
    (19, 'Cadillac', CURRENT_TIMESTAMP, true),
    (20, 'Buick', CURRENT_TIMESTAMP, true),
    (21, 'Subaru', CURRENT_TIMESTAMP, true),
    (22, 'Nissan', CURRENT_TIMESTAMP, true),
    (23, 'Mazda', CURRENT_TIMESTAMP, true),
    (24, 'Suzuki', CURRENT_TIMESTAMP, true),
    (25, 'Mitsubishi', CURRENT_TIMESTAMP, true),
    (26, 'Lexus', CURRENT_TIMESTAMP, true),
    (27, 'Infiniti', CURRENT_TIMESTAMP, true),
    (28, 'Acura', CURRENT_TIMESTAMP, true),
    (29, 'Rolls-Royce', CURRENT_TIMESTAMP, true),
    (30, 'Bentley', CURRENT_TIMESTAMP, true),
    (31, 'Aston Martin', CURRENT_TIMESTAMP, true),
    (32, 'Jaguar', CURRENT_TIMESTAMP, true),
    (33, 'Land Rover', CURRENT_TIMESTAMP, true),
    (34, 'Mini', CURRENT_TIMESTAMP, true),
    (35, 'Pagani', CURRENT_TIMESTAMP, true),
    (36, 'Opel', CURRENT_TIMESTAMP, true),
    (37, 'Peugeot', CURRENT_TIMESTAMP, true),
    (38, 'Renault', CURRENT_TIMESTAMP, true),
    (39, 'Citroën', CURRENT_TIMESTAMP, true),
    (40, 'Volvo', CURRENT_TIMESTAMP, true),
    (41, 'Kia', CURRENT_TIMESTAMP, true),
    (42, 'Hyundai', CURRENT_TIMESTAMP, true)
ON CONFLICT (id) DO NOTHING; -- Evita duplicação caso já existam
-- Insere marcas no banco de dados (caso ainda não estejam na tabela "marcas")
INSERT INTO public.marcas (id, nome, cadastro, ativo) VALUES
    (1, 'Chevrolet', CURRENT_TIMESTAMP, true),
    (2, 'Ford', CURRENT_TIMESTAMP, true),
    (3, 'Toyota', CURRENT_TIMESTAMP, true),
    (4, 'Honda', CURRENT_TIMESTAMP, true),
    (5, 'Ferrari', CURRENT_TIMESTAMP, true),
    (6, 'BMW', CURRENT_TIMESTAMP, true),
    (7, 'Mercedes-Benz', CURRENT_TIMESTAMP, true),
    (8, 'Volkswagen', CURRENT_TIMESTAMP, true),
    (9, 'Audi', CURRENT_TIMESTAMP, true),
    (10, 'Porsche', CURRENT_TIMESTAMP, true),
    (11, 'Lamborghini', CURRENT_TIMESTAMP, true),
    (12, 'Maserati', CURRENT_TIMESTAMP, true),
    (13, 'Alfa Romeo', CURRENT_TIMESTAMP, true),
    (14, 'Fiat', CURRENT_TIMESTAMP, true),
    (15, 'Tesla', CURRENT_TIMESTAMP, true),
    (16, 'Jeep', CURRENT_TIMESTAMP, true),
    (17, 'Dodge', CURRENT_TIMESTAMP, true),
    (18, 'Chrysler', CURRENT_TIMESTAMP, true),
    (19, 'Cadillac', CURRENT_TIMESTAMP, true),
    (20, 'Buick', CURRENT_TIMESTAMP, true),
    (21, 'Subaru', CURRENT_TIMESTAMP, true),
    (22, 'Nissan', CURRENT_TIMESTAMP, true),
    (23, 'Mazda', CURRENT_TIMESTAMP, true),
    (24, 'Suzuki', CURRENT_TIMESTAMP, true),
    (25, 'Mitsubishi', CURRENT_TIMESTAMP, true),
    (26, 'Lexus', CURRENT_TIMESTAMP, true),
    (27, 'Infiniti', CURRENT_TIMESTAMP, true),
    (28, 'Acura', CURRENT_TIMESTAMP, true),
    (29, 'Rolls-Royce', CURRENT_TIMESTAMP, true),
    (30, 'Bentley', CURRENT_TIMESTAMP, true),
    (31, 'Aston Martin', CURRENT_TIMESTAMP, true),
    (32, 'Jaguar', CURRENT_TIMESTAMP, true),
    (33, 'Land Rover', CURRENT_TIMESTAMP, true),
    (34, 'Mini', CURRENT_TIMESTAMP, true),
    (35, 'Pagani', CURRENT_TIMESTAMP, true),
    (36, 'Opel', CURRENT_TIMESTAMP, true),
    (37, 'Peugeot', CURRENT_TIMESTAMP, true),
    (38, 'Renault', CURRENT_TIMESTAMP, true),
    (39, 'Citroën', CURRENT_TIMESTAMP, true),
    (40, 'Volvo', CURRENT_TIMESTAMP, true),
    (41, 'Kia', CURRENT_TIMESTAMP, true),
    (42, 'Hyundai', CURRENT_TIMESTAMP, true)
ON CONFLICT (id) DO NOTHING; -- Evita duplicação caso já existam


-- Insere modelos relacionados às marcas
INSERT INTO public.modelos (id, nome, marca_id, cadastro, ativo) VALUES
    (1, 'Onix', 1, CURRENT_TIMESTAMP, true),
    (2, 'Cruze', 1, CURRENT_TIMESTAMP, true),
    (3, 'Ka', 2, CURRENT_TIMESTAMP, true),
    (4, 'Mustang', 2, CURRENT_TIMESTAMP, true),
    (5, 'Corolla', 3, CURRENT_TIMESTAMP, true),
    (6, 'Hilux', 3, CURRENT_TIMESTAMP, true),
    (7, 'Civic', 4, CURRENT_TIMESTAMP, true),
    (8, 'Fit', 4, CURRENT_TIMESTAMP, true),
    (9, '488 Spider', 5, CURRENT_TIMESTAMP, true),
    (10, '812 Superfast', 5, CURRENT_TIMESTAMP, true),
    (11, 'X5', 6, CURRENT_TIMESTAMP, true),
    (12, 'M3', 6, CURRENT_TIMESTAMP, true),
    (13, 'C-Class', 7, CURRENT_TIMESTAMP, true),
    (14, 'E-Class', 7, CURRENT_TIMESTAMP, true),
    (15, 'Golf', 8, CURRENT_TIMESTAMP, true),
    (16, 'Passat', 8, CURRENT_TIMESTAMP, true),
    (17, 'A4', 9, CURRENT_TIMESTAMP, true),
    (18, 'Q7', 9, CURRENT_TIMESTAMP, true),
    (19, '911', 10, CURRENT_TIMESTAMP, true),
    (20, 'Cayenne', 10, CURRENT_TIMESTAMP, true),
    (21, 'Huracan', 11, CURRENT_TIMESTAMP, true),
    (22, 'Aventador', 11, CURRENT_TIMESTAMP, true),
    (23, 'Ghibli', 12, CURRENT_TIMESTAMP, true),
    (24, 'Levante', 12, CURRENT_TIMESTAMP, true),
    (25, 'Giulia', 13, CURRENT_TIMESTAMP, true),
    (26, 'Stelvio', 13, CURRENT_TIMESTAMP, true),
    (27, '500', 14, CURRENT_TIMESTAMP, true),
    (28, 'Panda', 14, CURRENT_TIMESTAMP, true),
    (29, 'Model S', 15, CURRENT_TIMESTAMP, true),
    (30, 'Model X', 15, CURRENT_TIMESTAMP, true),
    (31, 'Wrangler', 16, CURRENT_TIMESTAMP, true),
    (32, 'Cherokee', 16, CURRENT_TIMESTAMP, true),
    (33, 'Challenger', 17, CURRENT_TIMESTAMP, true),
    (34, 'Charger', 17, CURRENT_TIMESTAMP, true),
    (35, 'Pacifica', 18, CURRENT_TIMESTAMP, true),
    (36, '300', 18, CURRENT_TIMESTAMP, true),
    (37, 'Escalade', 19, CURRENT_TIMESTAMP, true),
    (38, 'XT5', 19, CURRENT_TIMESTAMP, true),
    (39, 'Encore', 20, CURRENT_TIMESTAMP, true),
    (40, 'Enclave', 20, CURRENT_TIMESTAMP, true),
    (41, 'Outback', 21, CURRENT_TIMESTAMP, true),
    (42, 'Forester', 21, CURRENT_TIMESTAMP, true),
    (43, 'Altima', 22, CURRENT_TIMESTAMP, true),
    (44, 'Rogue', 22, CURRENT_TIMESTAMP, true),
    (45, 'CX-5', 23, CURRENT_TIMESTAMP, true),
    (46, 'Mazda3', 23, CURRENT_TIMESTAMP, true),
    (47, 'Swift', 24, CURRENT_TIMESTAMP, true),
    (48, 'Vitara', 24, CURRENT_TIMESTAMP, true),
    (49, 'Outlander', 25, CURRENT_TIMESTAMP, true),
    (50, 'Pajero', 25, CURRENT_TIMESTAMP, true),
    (51, 'RX', 26, CURRENT_TIMESTAMP, true),
    (52, 'NX', 26, CURRENT_TIMESTAMP, true),
    (53, 'Q50', 27, CURRENT_TIMESTAMP, true),
    (54, 'QX80', 27, CURRENT_TIMESTAMP, true),
    (55, 'MDX', 28, CURRENT_TIMESTAMP, true),
    (56, 'RDX', 28, CURRENT_TIMESTAMP, true),
    (57, 'Phantom', 29, CURRENT_TIMESTAMP, true),
    (58, 'Ghost', 29, CURRENT_TIMESTAMP, true),
    (59, 'Continental', 30, CURRENT_TIMESTAMP, true),
    (60, 'Bentayga', 30, CURRENT_TIMESTAMP, true),
    (61, 'DB11', 31, CURRENT_TIMESTAMP, true),
    (62, 'Vantage', 31, CURRENT_TIMESTAMP, true),
    (63, 'F-Type', 32, CURRENT_TIMESTAMP, true),
    (64, 'XF', 32, CURRENT_TIMESTAMP, true),
    (65, 'Discovery', 33, CURRENT_TIMESTAMP, true),
    (66, 'Range Rover', 33, CURRENT_TIMESTAMP, true),
    (67, 'Cooper', 34, CURRENT_TIMESTAMP, true),
    (68, 'Countryman', 34, CURRENT_TIMESTAMP, true),
    (69, 'Huayra', 35, CURRENT_TIMESTAMP, true),
    (70, 'Zonda', 35, CURRENT_TIMESTAMP, true),
    (71, 'Astra', 36, CURRENT_TIMESTAMP, true),
    (72, 'Corsa', 36, CURRENT_TIMESTAMP, true),
    (73, '208', 37, CURRENT_TIMESTAMP, true),
    (74, '3008', 37, CURRENT_TIMESTAMP, true),
    (75, 'Clio', 38, CURRENT_TIMESTAMP, true),
    (76, 'Captur', 38, CURRENT_TIMESTAMP, true),
    (77, 'C3', 39, CURRENT_TIMESTAMP, true),
    (78, 'C5 Aircross', 39, CURRENT_TIMESTAMP, true),
    (79, 'XC90', 40, CURRENT_TIMESTAMP, true),
    (80, 'S60', 40, CURRENT_TIMESTAMP, true),
    (81, 'Sportage', 41, CURRENT_TIMESTAMP, true),
    (82, 'Sorento', 41, CURRENT_TIMESTAMP, true),
    (83, 'Tucson', 42, CURRENT_TIMESTAMP, true),
    (84, 'Santa Fe', 42, CURRENT_TIMESTAMP, true)
ON CONFLICT (id) DO NOTHING; -- Evita duplicação caso já existam

